#!/bin/bash

set -e

lb config noauto \
    --color \
    --architectures amd64 \
    --mode debian \
    --distribution bookworm \
    --archive-areas "main contrib non-free non-free-firmware" \
    --mirror-bootstrap https://mirrors.ustc.edu.cn/debian \
    --mirror-chroot https://mirrors.ustc.edu.cn/debian \
    --mirror-chroot-security https://mirrors.ustc.edu.cn/debian-security \
    --mirror-binary https://mirrors.ustc.edu.cn/debian \
    --mirror-binary-security https://mirrors.ustc.edu.cn/debian-security \
    --mirror-debian-installer https://mirrors.ustc.edu.cn/debian \
    --cache-packages true \
    --cache-stages "bootstrap," `# bootstrap|chroot|rootfs` \
    --binary-filesystem fat32 \
    --binary-images iso-hybrid \
    --iso-application "DevOS" \
    --iso-publisher 'DevOS; https://gitee.com/jaysinco/devos; jaysinco@163.com' \
    --iso-volume 'DevOS $(date +%Y%m%d-%H:%M)' \
    --debian-installer live `# cdrom|netinst|netboot|businesscard|live|none` \
    --debian-installer-distribution bookworm \
    --debian-installer-gui true \
    --bootappend-live "boot=live components quiet splash" \
    --bootloader "syslinux,grub-efi" \
    --linux-packages "linux-image" \
    --linux-flavours amd64 \
    --apt-indices true \
    --apt-recommends true \
    --apt-secure false \
    --uefi-secure-boot enable \
    --security false \
    --updates false \
    --system live `# live|normal` \
    --debug \
    "${@}"
