#!/bin/bash

set -e

lb config noauto \
    --architectures amd64 \
    --mode debian \
    --distribution bookworm \
    --archive-areas "main contrib non-free non-free-firmware" \
    --mirror-bootstrap https://mirrors.163.com/debian \
    --mirror-chroot https://mirrors.163.com/debian \
    --mirror-chroot-security https://mirrors.163.com/debian-security \
    --mirror-binary https://mirrors.163.com/debian \
    --mirror-binary-security https://mirrors.163.com/debian-security \
    --mirror-debian-installer https://mirrors.163.com/debian \
    --cache-packages true \
    --binary-filesystem fat32 \
    --binary-images iso-hybrid \
    --iso-publisher 'DevOS; https://gitee.com/jaysinco/devos; jaysinco@163.com' \
    --iso-volume 'DevOS Bookworm $(date +%Y%m%d-%H:%M)' \
    --bootappend-live "boot=live components quiet splash hostname=sinco-dev username=sinco" \
    --bootloader syslinux \
    --linux-packages linux-image \
    --linux-flavours amd64 \
    --apt-indices false \
    --apt-recommends false \
    --apt-secure false \
    --security true \
    --updates true \
    --system live \
    "${@}"
